// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/Banner.vue')['default']
    CoverPlay: typeof import('./src/components/common/CoverPlay.vue')['default']
    Cube: typeof import('./src/components/Cube.vue')['default']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Error: typeof import('./src/components/common/Error.vue')['default']
    Footer: typeof import('./src/components/layout/footer/Footer.vue')['default']
    Header: typeof import('./src/components/layout/header/Header.vue')['default']
    IconPark: typeof import('./src/components/common/IconPark.vue')['default']
    Loading: typeof import('./src/components/common/Loading.vue')['default']
    Menu: typeof import('./src/components/layout/menu/Menu.vue')['default']
    MoreText: typeof import('./src/components/common/MoreText.vue')['default']
    PlayAction: typeof import('./src/components/layout/footer/PlayAction.vue')['default']
    PlayControll: typeof import('./src/components/layout/footer/PlayControll.vue')['default']
    PlayMode: typeof import('./src/components/layout/footer/PlayMode.vue')['default']
    PlayProgress: typeof import('./src/components/layout/footer/PlayProgress.vue')['default']
    PlaySong: typeof import('./src/components/layout/footer/PlaySong.vue')['default']
    PlayVoiceSlider: typeof import('./src/components/layout/footer/PlayVoiceSlider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/layout/header/Search.vue')['default']
    Slider: typeof import('./src/components/common/slider/Slider.vue')['default']
    SongCard: typeof import('./src/components/common/SongCard.vue')['default']
    SongListItem: typeof import('./src/components/common/SongListItem.vue')['default']
    Tabs: typeof import('./src/components/tabs/Tabs.vue')['default']
    Theme: typeof import('./src/components/layout/header/Theme.vue')['default']
    Title: typeof import('./src/components/common/Title.vue')['default']
    UserInfo: typeof import('./src/components/layout/header/UserInfo.vue')['default']
  }
}

export {}
